#https://docs.github.com/en/actions/quickstart
name: TSC Actions stellar
on: [push]
jobs:
  setup:
    runs-on: self-hosted
    steps:
      - run: echo $PATH
      - run: echo $HOME
      - run: echo $HOSTNAME
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} stellar hosted by PrincetonUniversity!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
      - name: prepare tsc in the workspace
        run: |
          cd ${{ github.workspace }}
          pwd
      - run: echo "ğŸ This job's status is ${{ job.status }}."

  build:
    needs: setup
    runs-on: self-hosted
    steps:
      - name: build tsc in the workspace
        run: |
          pwd
          cp -p ../../../compile.stellar .
          ./compile.stellar
      - run: echo "ğŸ This job's status is ${{ job.status }}."
 
  test:
    needs: build
    runs-on: self-hosted
    steps:
      - name: run tsc in the workspace
        run: |
          pwd
          cp -p ../../../run.stellar .
          ./run.stellar
      - run: echo "ğŸ This job's status is ${{ job.status }}."
      - name: check tsc in the workspace
        run: |
          pwd
          cp -p ../../../check.stellar .
          ./check.stellar
      - run: echo "ğŸ This job's status is ${{ job.status }}."
